services:
  docker_project:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      ENVIRONMENT: dev
    volumes:
      - ./src:/docker_project
